
name: Pull Request Test

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:        
      - name: Add Trello Comment 
        uses: DFE-Digital/github-actions/AddTrelloComment@link-trello-card-quote-bug-fix
        with:
          MESSAGE:      "Test Text"
          CARD:         "2696-fix-link-trello-card-github-action"          
          TRELLO-KEY:   ${{ secret.TRELLO_KEY}}
          TRELLO-TOKEN: "${{ secret.TRELLO_SECRET }}"
